export const productOneAction = {
    FETCH_ONE_DATA_REQUEST: "FETCH_ONE_DATA_REQUEST",
    FETCH_ONE_DATA_SUCCESS: "FETCH_ONE_DATA_SUCCESS",
    FETCH_ONE_DATA_FAILURE: "FETCH_ONE_DATA_FAILURE",
  };